//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HarvestTable
    {
        public int HarvestID { get; set; }
        public int SiteID { get; set; }
        public int MafID { get; set; }
        public string Type { get; set; }
        public int weight { get; set; }
        public string BeekeeperInitial { get; set; }
        public string Area { get; set; }
        public string Sitename { get; set; }
    
        public virtual SiteTable SiteTable { get; set; }
    }
}
